-- AlterTable
ALTER TABLE "Pedido" ADD COLUMN     "freteCents" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "fretePrazoDias" INTEGER,
ADD COLUMN     "freteServico" TEXT,
ADD COLUMN     "itensCents" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Produto" ADD COLUMN     "alturaCm" INTEGER NOT NULL DEFAULT 3,
ADD COLUMN     "comprimentoCm" INTEGER NOT NULL DEFAULT 32,
ADD COLUMN     "larguraCm" INTEGER NOT NULL DEFAULT 25,
ADD COLUMN     "pesoGramas" INTEGER NOT NULL DEFAULT 300;
